### ISSUE TITLE
compilation issues

### ISSUE THREAD

**Issue by zeos** [jpburstrom/scbno055#1]
Hi there!

After upgrading cmake on Bela to 3.25.2, I am trying to compile this extension. I got the SC sources at /root/supercollider
However, after clone-ing, creating the /build and running:

```cmake .. -DCMAKE_BUILD_TYPE=Release -DSC_PATH=/root/supercollider -DCMAKE_INSTALL_PREFIX=/usr/share/SuperCollider/Extensions```

so far so good.

but when I execute:

```
root@bela:~/scbno055/build# cmake --build . --config Release
[ 12%] Building CXX object CMakeFiles/BNO_scsynth.dir/plugins/BNO/BNO.cpp.o
/root/scbno055/plugins/BNO/BNO.cpp:2:18: fatal error: Bela.h: No such file or directory
 #include <Bela.h>
                  ^
compilation terminated.
CMakeFiles/BNO_scsynth.dir/build.make:75: recipe for target 'CMakeFiles/BNO_scsynth.dir/plugins/BNO/BNO.cpp.o' failed
make[2]: *** [CMakeFiles/BNO_scsynth.dir/plugins/BNO/BNO.cpp.o] Error 1
CMakeFiles/Makefile2:84: recipe for target 'CMakeFiles/BNO_scsynth.dir/all' failed
make[1]: *** [CMakeFiles/BNO_scsynth.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
```

How should I proceed to safely point cmake to find Bela.h (/root/Bela/include/Bela.h) and I guess respectively also the lib file when linking...

any help is appreciated. Thank you!

**Comment by jpburstrom** [comment]
I realize I have only cross-compiled this on a mac, where the script is setting the right paths: https://github.com/TheTechnobear/xcBela/blob/e8d4b029cf48bd717ac4d11a3451de6f9711a903/cmake/bela-toolchain.cmake#L34-L44

I could try revisiting it tomorrow on the Bela to see which flags are needed, but if you want you could try to cross-compile or use the lines from the linked script and adjust the paths to make it compile on the Bela.

**Comment by zeos** [comment]
Thanks for the quick reply!

Meantime, I made a few changes in the CMakelists.txt, based on the Trill repo, as follows:
```

####################################################################################################
# CMakeLists file for BNO
# Generated by Johannes Burström
# 2021-10-11
####################################################################################################

set(CMAKE_CXX_COMPILER_WORKS 1)
set(CMAKE_C_COMPILER_WORKS 1)

####################################################################################################
# basic project config
cmake_minimum_required(VERSION 3.7)
set(project_name "BNO")
set(CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake_modules ${CMAKE_MODULE_PATH})
#set(CMAKE_CXX_STANDARD 17)

####################################################################################################
# load modules
include(SuperColliderServerPlugin RESULT_VARIABLE server_plugin_found)
if(NOT server_plugin_found)
    message(FATAL_ERROR "Could not find server plugin functions module")
endif()

include(SuperColliderCompilerConfig RESULT_VARIABLE compiler_config_found)
if(NOT compiler_config_found)
    message(FATAL_ERROR "Could not find compiler config module")
endif()

# Windows - puts redistributable DLLs in install directory
include(InstallRequiredSystemLibraries)

sc_check_sc_path("${SC_PATH}")
message(STATUS "Found SuperCollider: ${SC_PATH}")
set(SC_PATH "${SC_PATH}" CACHE PATH
    "Path to SuperCollider source. Relative paths are treated as relative to this script" FORCE)

include("${SC_PATH}/SCVersion.txt")
message(STATUS "Building plugins for SuperCollider version: ${SC_VERSION}")

# set project here to avoid SCVersion.txt clobbering our version info
project(${project_name})
sc_do_initial_compiler_config() # do after setting project so compiler ID is available

if(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT OR NOT CMAKE_INSTALL_PREFIX)
    message(WARNING "No install prefix provided, defaulting to $BUILD_DIR/install")
    set(CMAKE_INSTALL_PREFIX "${CMAKE_BINARY_DIR}/install" CACHE PATH "Install prefix" FORCE)
endif()

message(STATUS "Install directory set to: ${CMAKE_INSTALL_PREFIX}")

####################################################################################################
# options
option(SUPERNOVA "Build plugins for supernova" ON)
option(SCSYNTH "Build plugins for scsynth" ON)
option(NATIVE "Optimize for native architecture" OFF)
option(STRICT "Use strict warning flags" OFF)
option(NOVA_SIMD "Build plugins with nova-simd support." ON)

####################################################################################################
# include libraries

if (NOVA_SIMD)
	add_definitions(-DNOVA_SIMD)
	include_directories(${SC_PATH}/external_libraries/nova-simd)
endif()

set(BELA_PATH /root/Bela/)

# Include all the search directories
include_directories(${SC_PATH}/include/plugin_interface)
include_directories(${SC_PATH}/include/common)
include_directories(${SC_PATH}/common)
include_directories(${BELA_PATH})
include_directories(${BELA_PATH}/include)
include_directories(${BELA_PATH}/lib)
include_directories(${BELA_PATH}/libraries)

####################################################################################################
# Begin target BNO

set(BNO_cpp_files
    plugins/BNO/BNO.cpp
    plugins/BNO/imu/Bela_BNO055.cpp
    plugins/BNO/imu/SC_BNO055.cpp
    plugins/BNO/imu/quaternion.h
    plugins/BNO/imu/matrix.h
    plugins/BNO/imu/imumaths.h
    plugins/BNO/imu/SC_BNO055.h
    plugins/BNO/imu/Bela_BNO055.h
    plugins/BNO/imu/vector.h
)
set(BNO_sc_files
    plugins/BNO/BNO.sc
)
set(BNO_schelp_files
    plugins/BNO/HelpSource/Classes/BNO.schelp
)

sc_add_server_plugin(
    "BNO/BNO" # desination directory
    "BNO" # target name
    "${BNO_cpp_files}"
    "${BNO_sc_files}"
    "${BNO_schelp_files}"
)

# End target BNO
####################################################################################################

####################################################################################################
# END PLUGIN TARGET DEFINITION
####################################################################################################

message(STATUS "Generating plugin targets done")

```

1. Changed the cake version with the one that is on the Bela (3.7)
2. I had to remove the c++17 constraint
3. added var to point to Bela.h, and the respective libs, headers...

executing it like that:

```
root@bela:~/scbno055/build# cmake -DSC_PATH=/root/supercollider -DBELA_PATH=/root/Bela/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/share/SuperCollider/Extensions ..
-- Found SuperCollider: /root/supercollider
-- Building plugins for SuperCollider version: 3.12.1
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test has_sse
-- Performing Test has_sse - Failed
-- Performing Test has_sse2
-- Performing Test has_sse2 - Failed
-- Performing Test has_sse_fp
-- Performing Test has_sse_fp - Failed
-- Install directory set to: /usr/share/SuperCollider/Extensions
-- Added server plugin target BNO_scsynth
-- Added server plugin target BNO_supernova
-- Generating plugin targets done
-- Configuring done
-- Generating done
-- Build files have been written to: /root/scbno055/build

```
So far, so good. however, after attempting to build it, I get this:

```
root@bela:~/scbno055/build# cmake --build . --config Release
Scanning dependencies of target BNO_scsynth
[ 12%] Building CXX object CMakeFiles/BNO_scsynth.dir/plugins/BNO/BNO.cpp.o
/root/scbno055/plugins/BNO/BNO.cpp:35:21: error: use of deleted function 'std::atomic<_Tp>::atomic(const std::atomic<_Tp>&) [with _Tp = float]'
     0.41, 0.51, 0.61};
                     ^
In file included from /root/scbno055/plugins/BNO/BNO.cpp:1:0:
/usr/include/c++/6/atomic:187:7: note: declared here
       atomic(const atomic&) = delete;
       ^~~~~~
/usr/include/c++/6/atomic:191:17: note:   after user-defined conversion: constexpr std::atomic<_Tp>::atomic(_Tp) [with _Tp = float]
       constexpr atomic(_Tp __i) noexcept : _M_i(__i) { }
                 ^~~~~~
/root/scbno055/plugins/BNO/BNO.cpp:35:21: error: use of deleted function 'std::atomic<_Tp>::atomic(const std::atomic<_Tp>&) [with _Tp = float]'
     0.41, 0.51, 0.61};
```

Any ideas?

best regards

**Comment by zeos** [comment]
some success:

by changing the code at line 32/35 to:

```
bnoState_t gData = {
    {0.1}, {0.2}, {0.3},
    {0.2}, {0.0}, {0.4},
    {0.3}, {0.0}, {0.5},
    {0.41}, {0.51}, {0.61} };
```

compiles just fine. Here is the output:

```
root@bela:~/scbno055/build# cmake --build . --config Release
[ 50%] Built target BNO_scsynth
[100%] Built target BNO_supernova
```

Then 

`cmake --build . --config Release --target install`

P.S. using:
1. cmake version 3.7.2 (instead of 3.12)
2.  gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516 
3. set(CMAKE_CXX_STANDARD 11) instead of 17

tomorrow I will check with the actual BNO sensor to see how things are going at the SC side.

best regards

**Comment by jpburstrom** [comment]
Thanks for the info! I've updated the repo with some of your changes, making it compilable with CMake 3.7 and C++11. I've also added binaries which hopefully should just work. 

Hope you got the sensor up and running!
